name: Lint, Build, and Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install flake8 and pytest
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Lint code
        run: flake8 .

      - name: Build project
        run: |
          echo "Simulating build step"
          # Optional: Replace this with your actual build command if needed
          python setup.py build || echo "No build step defined"

      - name: Run tests
        run: |
          echo "Running tests"
          pytest
